language: php

script:
  - echo "skipping tests"

after_success:
  - curl -u --ftp-create-dirs -T README.md ${SFTP_USER}:${SFTP_PASSWORD} ftp://awlo.org:21/public_html/testing/README.md
  - echo "successful"
    
notifications:
  slack: awlo:mqg8PBtixOi6JjasSaRdAsRl
