language: php

script:
  - echo "skipping tests"

after_success:
  - curl --ftp-create-dirs -T README.md ftp://${SFTP_USER}:${SFTP_PASSWORD}@awlo.org/public_html/testing/README.md
  - echo "successful"
    
notifications:
  slack: awlo:mqg8PBtixOi6JjasSaRdAsRl
