language: php

script:
  - echo "skipping tests"

after_success:
  - curl --ftp-create-dirs -T README.md ftp://awlo.org/testing/README.md --user ${SFTP_USER}:${SFTP_PASSWORD}
  - echo "successful"
    
notifications:
  slack: awlo:mqg8PBtixOi6JjasSaRdAsRl
