language: php

script:
  - echo "skipping tests"

after_success:
  - find . -type d -print -exec curl --ftp-create-dirs -T {} ftp://awlo.org/public_html/testing/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;
  - echo "successful"
    
notifications:
  slack: awlo:mqg8PBtixOi6JjasSaRdAsRl
